### ISSUE TITLE
Icons not working in the latest version

### ISSUE THREAD

**Issue by guilhermep** [Vectopus/Atlas-icons-flutter#1]
When using the latest version of the package (0.0.11), icons are replaced with question marks. Working well with 0.0.10. Flutter version: 3.7.1.

**Comment by james2doyle** [comment]
![flutter_01](https://user-images.githubusercontent.com/1425304/218343933-e4fc00de-e100-47e5-bc1e-c60934410564.png)

I'm having the same issue but getting this placeholder-style image instead

**Comment by mosamy19** [comment]
Hi @james2doyle @guilhermep, Thank you for reporting this issue. My apologies for inconvenience
I just fixed the issue and updated the package. Please use the latest version @0.0.12. 
Thank you
